-- 備品管理システム スキーマ（H2）

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOGIN_ID      VARCHAR(50)  NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    USER_NAME     VARCHAR(100) NOT NULL,
    ROLE          VARCHAR(20)  NOT NULL,
    DELETED       BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_AT    TIMESTAMP    NOT NULL,
    UPDATED_AT    TIMESTAMP    NOT NULL,
    CONSTRAINT UK_USERS_LOGIN_ID UNIQUE (LOGIN_ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
    CATEGORY_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    DISPLAY_ORDER INT          NOT NULL DEFAULT 0,
    DELETED       BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_AT    TIMESTAMP    NOT NULL,
    UPDATED_AT    TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS ITEMS (
    ITEM_ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    MANAGEMENT_NO     VARCHAR(20)  NOT NULL,
    ITEM_NAME         VARCHAR(100) NOT NULL,
    CATEGORY_ID       BIGINT       NOT NULL,
    PURCHASE_DATE     DATE,
    STORAGE_LOCATION  VARCHAR(100) NOT NULL,
    STATUS            VARCHAR(20)  NOT NULL,
    NOTE              VARCHAR(1000),
    VERSION           INT          NOT NULL DEFAULT 1,
    DELETED           BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_AT        TIMESTAMP    NOT NULL,
    UPDATED_AT        TIMESTAMP    NOT NULL,
    CONSTRAINT UK_ITEMS_MANAGEMENT_NO UNIQUE (MANAGEMENT_NO),
    CONSTRAINT FK_ITEMS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID)
);

CREATE TABLE IF NOT EXISTS LOANS (
    LOAN_ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    ITEM_ID             BIGINT      NOT NULL,
    USER_ID             BIGINT      NOT NULL,
    LOAN_DATE           DATE        NOT NULL,
    PLANNED_RETURN_DATE DATE        NOT NULL,
    ACTUAL_RETURN_DATE  DATE,
    STATUS              VARCHAR(20) NOT NULL,
    LOAN_NOTE           VARCHAR(1000),
    RETURN_NOTE         VARCHAR(1000),
    VERSION             INT         NOT NULL DEFAULT 1,
    CREATED_AT          TIMESTAMP   NOT NULL,
    UPDATED_AT          TIMESTAMP   NOT NULL,
    CONSTRAINT FK_LOANS_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID),
    CONSTRAINT FK_LOANS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_ITEMS_STATUS ON ITEMS (STATUS);
CREATE INDEX IF NOT EXISTS IDX_ITEMS_DELETED ON ITEMS (DELETED);
CREATE INDEX IF NOT EXISTS IDX_LOANS_ITEM_ID ON LOANS (ITEM_ID);
CREATE INDEX IF NOT EXISTS IDX_LOANS_USER_ID ON LOANS (USER_ID);
